version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: hostel-db
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - hostel-net

  web:
    build: .
    container_name: hostel-web
    depends_on:
      - db
    networks:
      - hostel-net

  loadbalancer:
    image: nginx:alpine
    container_name: hostel-lb
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - hostel-net

volumes:
  db_data:


networks:
  hostel-net:
